/*!
 * Open Realtime Connectivity JavaScript Library
 *
 * Copyright 2011, IBT, SA
 *
 * ORTC is part of our framework and it's powered by the world's first Real-Time Web Platform by IBT
 *
 * Join our movement to transform the World Wide Web into the Real-Time Web!
 *
 * Interested in Real-Time technology? See what we can do for your business today.
 * 
 * Transform your old website into an exciting Real-Time experience!
 * 
 * Improve the interaction with your visitor to a level never seen before
 * and increase visitor recurrency and loyalty.
 *
 * Visit us at www.realtime.co and learn more.
 *
 * Date: Tue Fev 11 2014 v2.1.16 1248
 */

function IbtRealTimeSJ(){var i,t,D,q,L,m,s,y,u,a,k,j,z,A,h,o,v,w,p,r,n;D=5E3;connectionMetadataMaxSize=256;var H=15,M=3,B=!1;q={};h={};p=t=v=y=s=m=!1;a=this;w=j=o=null;r=void 0;this.getId=function(){return L};this.setId=function(a){L=a};this.getUrl=function(){return k};this.setUrl=function(a){k=a;i=null};this.getClusterUrl=function(){return i};this.setClusterUrl=function(a){i=a;k=null};this.getConnectionTimeout=function(){return D};this.setConnectionTimeout=function(a){D=a};this.getIsConnected=function(){return m&&
a.sockjs!=null};this.getConnectionMetadata=function(){return z};this.setConnectionMetadata=function(a){z=a};this.getAnnouncementSubChannel=function(){return A};this.setAnnouncementSubChannel=function(a){A=a};this.getProtocol=function(){return r};this.setProtocol=function(a){r=a};this.getSessionId=function(){return n};this.getHeartbeatTime=function(){return H};this.setHeartbeatTime=function(b){b&&!isNaN(b)?b>60||b<10?e(a,"Heartbeat time is out of limits - Min: 10 | Max: 60"):H=b:e(a,"Invalid heartbeat time "+
b)};this.getHeartbeatFails=function(){return M};this.setHeartbeatFails=function(b){b&&!isNaN(b)?b>6||b<1?e(a,"Heartbeat fails is out of limits - Min: 1 | Max: 6"):M=b:e(a,"Invalid heartbeat fails "+b)};this.getHeartbeatActive=function(){return B};this.setHeartbeatActive=function(a){B=a};this.onReconnected=this.onReconnecting=this.onException=this.onUnsubscribed=this.onSubscribed=this.onDisconnected=this.onConnected=null;this.connect=function(b,d){if(m)e(a,"Already connected");else if(!k&&!i)e(a,"URL and Cluster URL are null or empty");
else if(b)if(d)if(k&&!ortcIsValidUrl(k))e(a,"Invalid URL");else if(i&&!ortcIsValidUrl(i))e(a,"Invalid Cluster URL");else if(ortcIsValidInput(b))if(ortcIsValidInput(d))if(ortcIsValidInput(A))if(z&&z.length>connectionMetadataMaxSize)e(a,"Connection metadata size exceeds the limit of "+connectionMetadataMaxSize+" characters");else{a.appKey=b;a.authToken=d;s=!0;u=!1;x(self);i&&i!=null?(i=i.ortcTreatUrl(),N()):(k=k.ortcTreatUrl(),a.sockjs=I(k));if(i&&i!=null&&i.indexOf("/ssl")>=0||k&&k.indexOf("https")>=
0)p?a.getConnectionTimeout()<3E5?a.getConnectionTimeout()<3E4?a.setConnectionTimeout(3E4):a.setConnectionTimeout((a.getConnectionTimeout()+10)*1E3):(u=!0,J()):a.setConnectionTimeout(3E4);if(!a.reconnectIntervalId&&!u)a.reconnectIntervalId=setInterval(function(){u?J():(a.sockjs==null&&!t&&O(),o!=null&&o+35E3<(new Date).getTime()&&(o=null,m&&K()))},a.getConnectionTimeout())}else e(a,"Announcement Subchannel has invalid characters");else e(a,"Authentication Token has invalid characters");else e(a,"Application Key has invalid characters");
else e(a,"Authentication Token is null or empty");else e(a,"Application Key is null or empty")};this.subscribe=function(b,d,f){if(m)if(b)if(ortcIsValidInput(b))if(h[b]&&h[b].isSubscribing)e(a,"Already subscribing to the channel '"+b+"'");else if(h[b]&&h[b].isSubscribed)e(a,"Already subscribed to the channel '"+b+"'");else if(b.length>100)e(a,"Channel size exceeds the limit of 100 characters");else if(ortcIsValidBoolean(d))if(ortcIsFunction(f)){if(a.sockjs!=null){var c=b.indexOf(":"),g=b,l=null;c>
0&&(g=b.substring(0,c+1)+"*");j&&j!=null&&(l=j[g]?j[g]:j[b]);j&&j!=null&&!l?e(a,"No permission found to subscribe to the channel '"+b+"'"):(h[b]?(h[b].isSubscribing=!0,h[b].isSubscribed=!1,h[b].subscribeOnReconnected=d,h[b].onMessageCallback=f):h[b]={isSubscribing:!0,isSubscribed:!1,subscribeOnReconnected:d,onMessageCallback:f},a.sockjs.send("subscribe;"+a.appKey+";"+a.authToken+";"+b+";"+l))}}else e(a,"The argument 'onMessageCallback' must be a function");else e(a,"The argument 'subscribeOnReconnected' must be a boolean");
else e(a,"Channel has invalid characters");else e(a,"Channel is null or empty");else e(a,"Not connected")};this.unsubscribe=function(b){m?b?ortcIsValidInput(b)?!h[b]||h[b]&&!h[b].isSubscribed?e(a,"Not subscribed to the channel "+b):b.length>100?e(a,"Channel size exceeds the limit of 100 characters"):a.sockjs!=null&&a.sockjs.send("unsubscribe;"+a.appKey+";"+b):e(a,"Channel has invalid characters"):e(a,"Channel is null or empty"):e(a,"Not connected")};this.send=function(b,d){if(!m||a.sockjs==null)e(a,
"Not connected");else if(b)if(ortcIsValidInput(b))if(d)if(ortcIsString(d))if(b.length>100)e(a,"Channel size exceeds the limit of 100 characters");else{var f=b.indexOf(":"),c=b,g=null;f>0&&(c=b.substring(0,f+1)+"*");j&&j!=null&&(g=j[c]?j[c]:j[b]);if(j&&j!=null&&!g)e(a,"No permission found to send to the channel '"+b+"'");else{var f=[],c=P(8),l,h=800-b.length;for(l=0;l<d.length;l+=h){if(d.length<=h){f.push(d);break}d.substring(l,l+h)&&f.push(d.substring(l,l+h))}for(l=1;l<=f.length;l++)a.sockjs.send("send;"+
a.appKey+";"+a.authToken+";"+b+";"+g+";"+c+"_"+l+"-"+f.length+"_"+f[l-1])}}else e(a,"Message must be a string");else e(a,"Message is null or empty");else e(a,"Channel has invalid characters");else e(a,"Channel is null or empty")};this.disconnect=function(){J();E();h={};!m&&!v?e(a,"Not connected"):K()};this.isSubscribed=function(b){if(m)if(b)if(ortcIsValidInput(b))return h[b]&&h[b].isSubscribed?h[b].isSubscribed:!1;else e(a,"Channel has invalid characters");else e(a,"Channel is null or empty");else e(a,
"Not connected")};this.presence=function(b,d){try{var f=null,c=!1,g=a.appKey,h=a.authToken;b.url?(f=b.url.ortcTreatUrl(),c=b.isCluster,g=b.applicationKey,h=b.authenticationToken):i&&i!=null?(f=i,c=!0):f=k.ortcTreatUrl();U({requestUrl:f,isCluster:c,appKey:g},function(a,c){a?d(a,null):V(c+"/presence/"+g+"/"+h+"/"+b.channel,d)})}catch(e){d("Unable to get presence data",null)}};var U=function(a,d){if(a.requestUrl&&a.isCluster){var f=F(),c="guid="+F(),c=a.appKey?c+"&appkey="+a.appKey:c;Q(a.requestUrl+
"/?"+c,f,function(a,b){a?d(null,SOCKET_SERVER):d(null,"Unable to get server from cluster");try{R(b)}catch(c){}})}else f=a.requestUrl.ortcTreatUrl(),d(null,f)},J=function(){if(a.reconnectIntervalId)clearInterval(a.reconnectIntervalId),a.reconnectIntervalId=null},x=function(a){if(a.validatedTimeoutId)clearTimeout(a.validatedTimeoutId),a.validatedTimeoutId=null},E=function(){u=!0;y=!1},S=function(a){if(!a.heartbeatInterval&&B)a.sockjs.send("b"),a.heartbeatInterval=setInterval(function(){B?a.sockjs.send("b"):
G(a)},H*1E3)},G=function(a){if(a.heartbeatInterval)clearInterval(a.heartbeatInterval),a.heartbeatInterval=null},C=function(a){a+="=";for(var d=document.cookie.split(";"),f=null,c=0;c<d.length;c++){for(var g=d[c];g.charAt(0)==" ";)g=g.substring(1,g.length);if(g.indexOf(a)==0){f=g.substring(a.length,g.length);break}}return f},P=function(a){for(var d="",f=0;f<a/4;f++)d+=((1+Math.random())*65536|0).toString(16).substring(1);return d},K=function(){G(a);w=null;p=s=m=!1;x(self);if(a.sockjs!=null)a.sockjs.close(),
a.sockjs=null},O=function(){G(a);s&&e(a,"Unable to connect");s=!0;if(a!=null&&a.onReconnecting!=null)a.onReconnecting(a);w=(new Date).getTime();i&&i!=null?N():a.sockjs=I(k)},N=function(){var b=F(),d="guid="+F(),d=a.appKey?d+"&appkey="+a.appKey:d;Q(i+"/?"+d,b,function(b,d){b&&(k=SOCKET_SERVER,I(a.getUrl()));try{R(d)}catch(g){}})},R=function(a){for(var d=document.getElementsByTagName("head")[0].children,f=[],c=0;c<d.length;c++)d[c].attributes!=null&&d[c].attributes.ortcScriptId&&d[c].attributes.ortcScriptId.value==
a&&f.push(c);for(var g in f)document.getElementsByTagName("head")[0].removeChild(d[f[g]])},Q=function(a,d,f){var c=document.createElement("script");c.type="text/javascript";c.setAttribute("ortcScriptId",d);t=!0;c.readyState?c.onreadystatechange=function(){if(c.readyState=="loaded"||c.readyState=="complete")t=!1,c.onreadystatechange=null,typeof SOCKET_SERVER!="undefined"&&SOCKET_SERVER.indexOf("undefined")<0&&SOCKET_SERVER.indexOf("unknown_server")<0?f(!0,d):f(!1,d)}:c.onload=function(){t=!1;typeof SOCKET_SERVER!=
"undefined"&&SOCKET_SERVER.indexOf("undefined")<0&&SOCKET_SERVER.indexOf("unknown_server")<0?f(!0,d):f(!1,d)};c.onerror=function(){t=!1};c.src=a;document.getElementsByTagName("head")[0].appendChild(c)},F=function(){var a=function(){return((1+Math.random())*65536|0).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()},I=function(b){if(a.sockjs==null){navigator&&navigator.userAgent&&navigator.userAgent.indexOf("PlayStation Vita")>=0&&(r="jsonp-polling");a.sockjs=new SockJS(b+
"/broadcast",r);if(!a.sslFallback)a.validatedTimeoutId=setTimeout(function(){a.sslFallback=!0;E();K();p=v=!0;r=void 0;if(!("ActiveXObject"in window))if(i&&i!=null){if(i.indexOf("ssl/")<0){var d=i.search(/\/([\d.]*)\/$/);i=d>-1?i.substring(0,d+1)+"ssl/"+i.substring(d+1,i.length):i.substring(0,i.lastIndexOf("/")+1)+"ssl/"+i.substring(i.lastIndexOf("/")+1)}}else k=k.replace("http://","https://")},5E3);a.sockjs.onopen=function(){r=a.sockjs.protocol;o=(new Date).getTime();if(y)n="";else if(n=C("ortcsession-"+
a.appKey+"-s"),!n)(n=C("ortcsession-"+a.appKey))||(n=P(16)),document.cookie="ortcsession-"+a.appKey+"-s="+n+"; path=/",C("ortcsession-"+a.appKey+"-s")||(n="");var d=B?";"+a.getHeartbeatTime()+";"+a.getHeartbeatFails()+";":"";a.sockjs.send("validate;"+a.appKey+";"+a.authToken+";"+(A?A:"")+";"+n+";"+z+d)};a.sockjs.onclose=function(d){G(a);if(a.sockjs!=null)a.sockjs.close(),a.sockjs=null;j=null;d.code!=1E3?(m&&(s=m=!1,r=void 0,T(a)),u||(!w||w+D<(new Date).getTime())&&O()):v||(s=m=!1,r=void 0,T(a));p&&
(a.connect(a.appKey,a.authToken),p=!1);v=!1};a.sockjs.onmessage=function(d){o=(new Date).getTime();var b=d.data,d=b.ch,b=b.m,c=/^(\w[^_]*)_{1}(\d*)-{1}(\d*)_{1}([\s\S.]*)$/.exec(b),g=null,e=1,i=1,j=!1;c&&c.length>0&&(c[1]&&(g=c[1]),c[2]&&(e=c[2]),c[3]&&(i=c[3]),c[4]&&(b=c[4]));if(g){q[g]||(q[g]={});q[g][e]=b;var c=0,k;for(k in q[g])c++;c==i&&(j=!0)}else j=!0;if(j){if(g){b="";for(k=1;k<=i;k++)b+=q[g][k],delete q[g][k];delete q[g]}if(a!=null&&h[d]&&h[d].isSubscribed&&h[d].onMessageCallback!=null)h[d].onMessageCallback(a,
d,b)}};a.sockjs.onortcsubscribed=function(b){o=(new Date).getTime();b=b.data;if(h[b])h[b].isSubscribing=!1,h[b].isSubscribed=!0;if(a!=null&&a.onSubscribed!=null&&b!=null)a.onSubscribed(a,b)};a.sockjs.onortcunsubscribed=function(b){o=(new Date).getTime();b=b.data;if(h[b])h[b].isSubscribed=!1;if(a!=null&&a.onUnsubscribed!=null&&b!=null)a.onUnsubscribed(a,b)};a.sockjs.onheartbeat=function(){o=(new Date).getTime()};a.sockjs.onortcvalidated=function(b){var f=30;if(b.data)j=b.data;if(b.set)f=b.set;x(a);
s=p=!1;m=!0;w=null;if(n){if(!C("ortcsession-"+a.appKey+"-s"))document.cookie="ortcsession-"+a.appKey+"-s="+n+"; path=/";if(!C("ortcsession-"+a.appKey)){var b="ortcsession-"+a.appKey,c=n,g="";f&&(g=new Date,g.setTime(g.getTime()+f*6E4),g="; expires="+g.toGMTString());document.cookie=b+"="+c+g+"; path=/"}}if(y){var b={},e;for(e in h)h[e].subscribeOnReconnected==!0&&(h[e].isSubscribing||h[e].isSubscribed)?(h[e].isSubscribing=!0,h[e].isSubscribed=!1,c=e.indexOf(":"),f=e,g=null,c>0&&(f=e.substring(0,c+
1)+"*"),j&&j!=null&&(g=j[f]?j[f]:j[e]),a.sockjs.send("subscribe;"+a.appKey+";"+a.authToken+";"+e+";"+g)):b[e]=e;for(var i in b)delete h[i];q={};a!=null&&a.onReconnected!=null&&(S(a),a.onReconnected(a))}else y=!0,a!=null&&a.onConnected!=null&&(S(a),a.onConnected(a))};a.sockjs.onortcerror=function(b){o=(new Date).getTime();var f=b.data,b=f.op,c=f.ch,f=f.ex?f.ex:f;e(a,f);switch(b){case "validate":f.indexOf("busy")<0?(v=!0,x(a),p=!1,E()):(x(a),p=!1);break;case "subscribe":if(c&&h[c])h[c].isSubscribing=
!1;break;case "subscribe_maxsize":case "unsubscribe_maxsize":case "shutdown":x(a);p=!1;break;case "send_maxsize":if(c&&h[c])h[c].isSubscribing=!1;E()}}}return a.sockjs},V=function(a,d){var e=document.head?document.head:document.getElementsByTagName("head")[0],c=document.createElement("script"),g="ortcJsonp"+ +new Date,h=setTimeout(function(){try{d("Unable to get data",null),window[g]=void 0,delete window[g],e.removeChild(c)}catch(a){}},15E3);window[g]=function(a){clearTimeout(h);a.error?d(a.error,
null):d(null,a.content);try{window[g]=void 0,delete window[g],e.removeChild(c)}catch(b){}};c.setAttribute("src",a+"?callback="+g);e.appendChild(c)},T=function(a){if(a!=null&&a.onDisconnected!=null)a.onDisconnected(a)},e=function(a,d){if(a!=null&&a.onException!=null)a.onException(a,d)}};
